@startuml
autonumber
'hide footbox
actor "Colaborador de Organização" as ADM

participant ":EspecificarTarefaUI" as UI
participant ":EspecificarTarefaController" as CTRL
participant "AplicacaoPOT" as _APP
participant "app\n:AplicacaoPOT" as APP
participant "sessao\n:SessaoUtilizador" as SESSAO
participant ":Plataforma" as PLAT
participant "rcat:Registo\nCategorias" as RCAT
participant "rorgs:Registo\nOrganizacoes" as RORGS
participant "org\n:Organizacao" as ORG
participant "lt\n:ListaTarefas" as LTASKS
participant "tarefa\n:Tarefa" as TAREFA
participant "lc\n:List<Categoria>" as LIST_CAT

activate ADM
ADM -> UI : inicia a especificação de uma tarefa
activate UI
UI --> ADM : solicita os dados \n(i.e. referência única por organização, designação, descrição informal e de caráter técnico, estimativa de duração e custo)
deactivate UI

ADM -> UI : introduz os dados solicitados
activate UI

UI -> CTRL : lc=getCategorias()
activate CTRL

CTRL -> PLAT : rcat = getRegistoCategorias()
activate PLAT
deactivate PLAT

CTRL -> RCAT : lc=getCategorias()
activate RCAT
deactivate RCAT
deactivate CTRL

UI --> ADM : mostra a lista de categorias e pede para selecionar uma
deactivate UI

ADM -> UI : seleciona uma categoria
activate UI

UI -> CTRL : novaTarefa(ref,dsig,dsInf,dsTec,duracEst,custoEst,catId)
activate CTRL

CTRL -> RCAT : cat=getCategoriaById(catId)
activate RCAT
deactivate RCAT

CTRL -> _APP: app = getInstance()
activate _APP
|||
deactivate _APP

CTRL -> APP: sessao = getSessaoAtual()
activate APP
|||
deactivate APP

CTRL -> SESSAO: email = getEmailUtilizador()
activate SESSAO
deactivate SESSAO

CTRL -> PLAT: rorgs = getRegistoOrganizacoes()
activate PLAT
deactivate PLAT

CTRL -> RORGS: org = getOrganizacaoByEmailUtilizador(email)
activate RORGS
deactivate RORGS

CTRL -> ORG: lt = getListaTarefas()
activate ORG
deactivate ORG

CTRL -> LTASKS: tarefa=novaTarefa(ref,dsig,dsInf,dsTec,duracEst,custoEst,cat)
activate LTASKS

LTASKS --> TAREFA**: create(ref,dsig,dsInf,dsTec,duracEst,custoEst,cat)
LTASKS -> LTASKS: validaTarefa(tarefa)

UI --> ADM: apresenta os dados e solicita confirmação
deactivate LTASKS
deactivate CTRL
deactivate UI

ADM -> UI : confirma os dados
activate UI
UI -> CTRL : registaTarefa()
activate CTRL

CTRL -> LTASKS : registaTarefa(tarefa)
activate LTASKS

LTASKS -> LTASKS: validaTarefa(tarefa)
LTASKS -> LTASKS: addTarefa(tarefa)

UI --> ADM : informa do sucesso da operação
deactivate LTASKS
deactivate CTRL
deactivate UI

deactivate ADM

@enduml
